[package]
name = "cppdvt"
version = "0.9.0"
description = "Utilities for declaring and using C++ virtual function tables"
authors = ["[aka]bomb"]
license = "MIT"
edition = "2021"

[features]
default = ["macros"]
macros = []

[dependencies]
